services:
  db:
    image: mysql:latest
    env_file: .env
    ports:
      - 3306:3306
  adminer:
    image: adminer:latest
    environment:
      - ADMINER_DESIGN="hydra"
    ports:
      - 8080:8080
